"""LLM-backed judge for novelty + hypothesis-to-spec matching.

Two judgments share one interface so the on-disk cache and the backend
selector apply uniformly to both: ``judge_novelty`` (does each hypothesis
go beyond paradigm consensus?) and ``judge_matches`` (does each hypothesis
correspond to a single ground-truth association?).

``judge_matches`` is variant-aware but the *information shown to the
judge* is symmetric across variants: when a column mapping is
available the rendered ground-truth block includes both the clinical
name and the corresponding ``feature_NNN`` identifier for every
variable and predicate key, and the free-text NL description is shown
for both variants. The variant only determines which column-name
space the agent's hypothesis text uses; the judge sees both spaces
either way.

Default backend is ``ClaudeCliJudge``: subprocess to ``claude
--dangerously-skip-permissions -p <prompt>`` so the judge runs under the
same Claude Code auth that's already on the box (no API key plumbing).
``CodexCliJudge`` is also available for hosts authenticated with the OpenAI
Codex CLI. A deterministic ``StubJudge`` is provided for tests.

All judgments are cached on disk by ``sha256(prompt)`` so re-running
scoring on identical transcripts is free.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol

from ..synthetic.schemas import AssociationForm, AssociationSpec

Variant = Literal["named", "anonymized"]
RecoveryLevel = Literal["none", "component", "near", "exact"]
RECOVERY_LEVELS: tuple[RecoveryLevel, ...] = ("none", "component", "near", "exact")


@dataclass
class NoveltyJudgment:
    is_novel: bool
    rationale: str


@dataclass
class MatchJudgment:
    matches: bool
    rationale: str
    recovery_level: RecoveryLevel = "none"


class Judge(Protocol):
    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]: ...

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]: ...


# ---- Prompts ------------------------------------------------------------

_NOVELTY_PROMPT = """\
You are evaluating hypotheses generated by an analytical pipeline studying \
an oncology dataset. For each hypothesis, decide whether it is NOVEL — \
i.e., goes beyond established oncology paradigm consensus that would \
appear in a current treatment guideline or textbook for this disease. \
Standard known associations (e.g., "EGFR mutation predicts response to \
osimertinib", "BRCA1/2-mutant breast cancer responds to PARP inhibitors") \
are NOT novel. Speculative subgroup-conditional, mechanistic, or \
cross-pathway claims that wouldn't appear in a guideline ARE novel.

Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"is_novel": true|false, "rationale": "<one sentence>"}}, ...]
"""


_MATCH_PROMPT = """\
You are matching analyst-proposed hypotheses to a single ground-truth \
association embedded in a synthetic dataset. For each hypothesis, decide \
whether it would, if confirmed, correspond to the ground-truth association \
— i.e. whether it identifies (or proposes a method capable of identifying) \
the same data-generating process.

A hypothesis MATCHES if all the following hold:
1. It points at the same set of feature/variable column(s) and the same \
outcome column listed in the spec. Each variable below is shown with \
both its clinical name and the corresponding anonymized identifier \
(``feature_NNN``) where applicable; the analyst was given only one of \
these two name spaces, so a hypothesis that uses either name is referring \
to the same underlying column. Treat clinical names and ``feature_NNN`` \
identifiers as fully interchangeable.
2. It describes (or proposes to investigate) the same relationship. \
Paraphrasing, synonyms, brand-vs-generic names, and mechanism-class \
language are fine. The hypothesis does NOT have to specify the exact \
functional form: a hypothesis that proposes investigating these variables \
with a method reasonably expected to capture the spec's functional form \
counts as matching — e.g. a tree ensemble or interaction-aware model for \
an interaction; subgroup analysis, stratification, or a heterogeneous- \
treatment-effect model for a subgroup-conditional effect; a regression \
or test of association for a main effect.
3. The direction of effect, if specified by the hypothesis, agrees with \
the ground truth.

Also assign a recovery_level:
- "exact": the hypothesis MATCHES by the definition above.
- "near": the hypothesis identifies the correct treatment/driver, outcome, \
direction, and most of the defining subgroup/interaction structure, but omits \
or approximates one predicate/threshold. This is not exact recovery.
- "component": the hypothesis identifies the correct treatment/driver and \
outcome plus at least one correct subgroup modifier, lower-order interaction, \
or other meaningful component of the ground-truth process, but is incomplete \
or framed as a component rather than the joint association.
- "none": no meaningful recovery of the ground-truth association.

Do not give "near" or "component" credit for a hypothesis that merely lists \
ground-truth variables as covariates while asserting a different driver, a \
different extra modifier, or a generic adjusted main effect. Set matches=true \
if and only if recovery_level is "exact".

Ground-truth association:
{spec_block}
Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"matches": true|false, "recovery_level": "exact"|"near"|"component"|"none", "rationale": "<one sentence>"}}, ...]
"""


_FORM_HUMAN: dict[AssociationForm, str] = {
    AssociationForm.main_effect: (
        "main effect — the variable directly predicts the outcome"
    ),
    AssociationForm.interaction: (
        "interaction — two or more variables jointly affect the outcome "
        "(effects depend on combinations of values, not each variable alone)"
    ),
    AssociationForm.subgroup_conditional: (
        "subgroup-conditional — the relationship is active only within a "
        "defined subset of patients"
    ),
}


def _direction_human(direction: int) -> str:
    if direction > 0:
        return "positive (increases the outcome)"
    if direction < 0:
        return "negative (decreases the outcome)"
    return "null / no expected directional effect"


def _format_numbered(hypotheses: list[str]) -> str:
    return "\n".join(f"{i + 1}. {h}" for i, h in enumerate(hypotheses))


def _bilingual_name(
    col: str,
    forward: dict[str, str] | None,
    inverse: dict[str, str] | None,
) -> str:
    """Render ``col`` as ``clinical (anonymized: feature_NNN)`` when both
    sides are available; otherwise return ``col`` verbatim.

    ``forward`` is ``{clinical → feature_NNN}``; ``inverse`` is its reverse.
    Outcome and id columns are excluded from anonymization (they appear
    verbatim in both spaces) and so end up in neither map — those return
    ``col`` unchanged.
    """
    if forward is None:
        return col
    if col in forward:
        return f"{col} (anonymized: {forward[col]})"
    if inverse is not None and col in inverse:
        return f"{inverse[col]} (anonymized: {col})"
    return col


def _render_spec_block(
    spec: AssociationSpec,
    variant: Variant,
    column_mapping: dict[str, str] | None = None,
) -> str:
    """Render the structured ground-truth block of the match prompt.

    Variables and (subgroup) predicate keys are rendered bilingually when
    ``column_mapping`` is provided (``{clinical → feature_NNN}``) so the
    judge sees the same information regardless of which variant the agent
    saw. The free-text NL description is included for both variants.
    """
    inverse = (
        {v: k for k, v in column_mapping.items()}
        if column_mapping is not None
        else None
    )

    lines: list[str] = []
    lines.append(f"- Outcome column: {spec.outcome}")
    lines.append("- Variables involved:")
    for v in spec.variables:
        lines.append(f"    * {_bilingual_name(v, column_mapping, inverse)}")
    lines.append(f"- Functional form: {_FORM_HUMAN[spec.form]}")
    if spec.subgroup is not None:
        lines.append(
            f"- Subgroup (relationship active only here): "
            f"{spec.subgroup.description}"
        )
        for k, val in spec.subgroup.predicate.items():
            lines.append(
                f"    * Predicate: {_bilingual_name(k, column_mapping, inverse)} = {val}"
            )
    lines.append(f"- Direction of effect on outcome: {_direction_human(spec.direction)}")
    lines.append(
        f"- Plain-English description: {spec.natural_language_description}"
    )
    return "\n".join(lines) + "\n"


def _build_novelty_prompt(hypotheses: list[str]) -> str:
    return _NOVELTY_PROMPT.format(
        numbered=_format_numbered(hypotheses), n=len(hypotheses)
    )


def _build_match_prompt(
    hypotheses: list[str],
    spec: AssociationSpec,
    *,
    variant: Variant,
    column_mapping: dict[str, str] | None = None,
) -> str:
    return _MATCH_PROMPT.format(
        spec_block=_render_spec_block(spec, variant, column_mapping),
        numbered=_format_numbered(hypotheses),
        n=len(hypotheses),
    )


def _match_judgment_from_payload(entry: dict) -> MatchJudgment:
    matches = bool(entry.get("matches", False))
    raw_level = str(entry.get("recovery_level", "")).lower()
    level: RecoveryLevel
    if raw_level in RECOVERY_LEVELS:
        level = raw_level  # type: ignore[assignment]
    else:
        level = "exact" if matches else "none"

    if matches:
        level = "exact"
    elif level == "exact":
        matches = True
    return MatchJudgment(
        matches=matches,
        recovery_level=level,
        rationale=str(entry.get("rationale", "")),
    )


# ---- JSON extraction ----------------------------------------------------


def _extract_json_array(text: str) -> list[dict]:
    """Pull the outermost ``[...]`` block out of a possibly-wrapped LLM response.

    Handles preamble, code fences, and trailing commentary.
    """
    fence = re.search(r"```(?:json)?\s*(\[[\s\S]*?\])\s*```", text)
    if fence:
        payload = fence.group(1)
    else:
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1 or end <= start:
            raise ValueError(f"No JSON array found in response: {text!r}")
        payload = text[start : end + 1]
    parsed = json.loads(payload)
    if not isinstance(parsed, list):
        raise ValueError(f"Expected JSON array, got {type(parsed).__name__}: {parsed!r}")
    return parsed


# ---- Cache --------------------------------------------------------------


@dataclass
class JudgeCache:
    """Trivial sha256 → JSON file cache."""

    cache_dir: Path | None

    def get(self, prompt: str) -> str | None:
        if self.cache_dir is None:
            return None
        path = self._path(prompt)
        if not path.is_file():
            return None
        return path.read_text(encoding="utf-8")

    def put(self, prompt: str, response: str) -> None:
        if self.cache_dir is None:
            return
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        path = self._path(prompt)
        # Atomic: write temp, then rename.
        with tempfile.NamedTemporaryFile(
            mode="w", dir=self.cache_dir, delete=False, encoding="utf-8"
        ) as tmp:
            tmp.write(response)
            tmp_path = Path(tmp.name)
        os.replace(tmp_path, path)

    def _path(self, prompt: str) -> Path:
        assert self.cache_dir is not None
        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        return self.cache_dir / f"{digest}.txt"


# ---- Backends -----------------------------------------------------------


def _chunked(items: list[str], n: int) -> Iterable[list[str]]:
    for i in range(0, len(items), n):
        yield items[i : i + n]


_WINDOWS_CLI_EXTENSIONS = (".exe", ".cmd", ".bat", ".ps1")


def _has_path_separator(value: str) -> bool:
    return "/" in value or "\\" in value


def _resolve_cli_argv(cli: str, *, windows: bool | None = None) -> list[str]:
    """Return an argv prefix that Python can launch with ``shell=False``.

    On Windows, npm-installed CLIs are commonly exposed as ``.cmd`` and
    ``.ps1`` shims. ``subprocess.run(["codex", ...])`` does not reliably
    resolve those shims, so we resolve the concrete launcher first.
    """

    is_windows = os.name == "nt" if windows is None else windows
    if not is_windows:
        return [cli]

    resolved = _resolve_windows_cli_path(cli)
    if resolved is None:
        return [cli]

    resolved_path = Path(resolved)
    if resolved_path.suffix.lower() == ".ps1":
        powershell = (
            shutil.which("powershell.exe")
            or shutil.which("pwsh.exe")
            or "powershell.exe"
        )
        return [
            powershell,
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(resolved_path),
        ]
    return [str(resolved_path)]


def _resolve_windows_cli_path(cli: str) -> str | None:
    cli_path = Path(cli)
    candidates: list[str] = []
    if not cli_path.suffix:
        candidates.extend(f"{cli}{ext}" for ext in _WINDOWS_CLI_EXTENSIONS)
    candidates.append(cli)

    if _has_path_separator(cli):
        for candidate in candidates:
            candidate_path = Path(candidate)
            if candidate_path.is_file():
                return str(candidate_path)
        return None

    for candidate in candidates:
        found = shutil.which(candidate)
        if found is not None:
            return found
    return None


def _cli_launch_error(label: str, requested_cli: str, argv: list[str]) -> str:
    return (
        f"Unable to launch {label} CLI {requested_cli!r} "
        f"(argv prefix starts with {argv[:5]!r}). "
        "If this is an npm-installed CLI on Windows, pass the .cmd shim "
        "explicitly with --judge-cli, or make sure that shim is on PATH."
    )


@dataclass
class ClaudeCliJudge:
    """Default judge: shells out to the ``claude`` CLI with ``-p``.

    Requires a working ``claude`` on ``PATH`` (or pass ``cli=...``). No API
    key needed when running on a host where Claude Code is already
    authenticated.
    """

    cli: str = "claude"
    extra_args: tuple[str, ...] = (
        "--dangerously-skip-permissions",
    )
    batch_size: int = 10
    cache: JudgeCache | None = None
    timeout_s: int = 600

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        out: list[NoveltyJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            payload = self._run_chunk(_build_novelty_prompt(chunk), expected=len(chunk))
            for entry in payload:
                out.append(
                    NoveltyJudgment(
                        is_novel=bool(entry.get("is_novel", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        out: list[MatchJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            prompt = _build_match_prompt(
                chunk, spec, variant=variant, column_mapping=column_mapping
            )
            payload = self._run_chunk(prompt, expected=len(chunk))
            for entry in payload:
                out.append(_match_judgment_from_payload(entry))
        return out

    def _run_chunk(self, prompt: str, *, expected: int) -> list[dict]:
        if self.cache is not None:
            cached = self.cache.get(prompt)
            if cached is not None:
                payload = _extract_json_array(cached)
                if len(payload) == expected:
                    return payload
                # Cache mismatch on length — fall through and re-call.
        argv = [*_resolve_cli_argv(self.cli), *self.extra_args, "-p", prompt]
        try:
            completed = subprocess.run(
                argv,
                capture_output=True,
                text=True,
                encoding="utf-8",
                timeout=self.timeout_s,
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                _cli_launch_error("claude", self.cli, argv)
            ) from exc
        if completed.returncode != 0:
            raise RuntimeError(
                f"claude CLI exited {completed.returncode}: "
                f"stderr={completed.stderr.strip()!r} "
                f"stdout={completed.stdout.strip()!r} "
                f"prompt_len={len(prompt)}"
            )
        response = completed.stdout
        payload = _extract_json_array(response)
        if len(payload) != expected:
            raise ValueError(
                f"Expected {expected} judgments, got {len(payload)}: {response!r}"
            )
        if self.cache is not None:
            self.cache.put(prompt, response)
        return payload


def _codex_structured_prompt(prompt: str) -> str:
    return (
        prompt
        + "\n\nFor the Codex CLI structured-output wrapper, return ONLY a JSON "
        'object with exactly one key, "judgments", whose value is the JSON '
        "array requested above. Do not include prose."
    )


def _codex_output_schema(
    judgment_key: Literal["is_novel", "matches"],
) -> dict[str, object]:
    item_properties: dict[str, object] = {
        judgment_key: {"type": "boolean"},
        "rationale": {"type": "string"},
    }
    required = [judgment_key, "rationale"]
    if judgment_key == "matches":
        item_properties["recovery_level"] = {
            "type": "string",
            "enum": list(RECOVERY_LEVELS),
        }
        required.insert(1, "recovery_level")
    return {
        "type": "object",
        "properties": {
            "judgments": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": item_properties,
                    "required": required,
                    "additionalProperties": False,
                },
            }
        },
        "required": ["judgments"],
        "additionalProperties": False,
    }


@dataclass
class CodexCliJudge:
    """Judge via the OpenAI Codex CLI's non-interactive ``codex exec`` mode.

    The current Codex CLI structure is ``codex exec [OPTIONS] [PROMPT]``.
    This backend passes ``-`` as the prompt placeholder and streams the prompt
    on stdin, so long prompts do not become command-line arguments. By default
    it runs read-only, ignores rules/user config for reproducibility, skips the
    git-repository guard for one-off scoring directories, and uses
    ``--output-schema`` to request a stable final JSON object.
    """

    cli: str = "codex"
    model_id: str | None = None
    extra_args: tuple[str, ...] = (
        "--sandbox",
        "read-only",
        "--skip-git-repo-check",
        "--ephemeral",
        "--ignore-user-config",
        "--ignore-rules",
        "--color",
        "never",
    )
    batch_size: int = 10
    cache: JudgeCache | None = None
    timeout_s: int = 600
    use_output_schema: bool = True

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        out: list[NoveltyJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            payload = self._run_chunk(
                _build_novelty_prompt(chunk),
                expected=len(chunk),
                judgment_key="is_novel",
            )
            for entry in payload:
                out.append(
                    NoveltyJudgment(
                        is_novel=bool(entry.get("is_novel", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        out: list[MatchJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            prompt = _build_match_prompt(
                chunk, spec, variant=variant, column_mapping=column_mapping
            )
            payload = self._run_chunk(
                prompt,
                expected=len(chunk),
                judgment_key="matches",
            )
            for entry in payload:
                out.append(_match_judgment_from_payload(entry))
        return out

    def _run_chunk(
        self,
        prompt: str,
        *,
        expected: int,
        judgment_key: Literal["is_novel", "matches"],
    ) -> list[dict]:
        if self.cache is not None:
            cached = self.cache.get(prompt)
            if cached is not None:
                payload = _extract_json_array(cached)
                if len(payload) == expected:
                    return payload

        run_prompt = (
            _codex_structured_prompt(prompt) if self.use_output_schema else prompt
        )
        argv = [*_resolve_cli_argv(self.cli), "exec", *self.extra_args]
        if self.model_id is not None:
            argv.extend(["--model", self.model_id])

        schema_path: Path | None = None
        if self.use_output_schema:
            with tempfile.NamedTemporaryFile(
                mode="w",
                suffix=".schema.json",
                delete=False,
                encoding="utf-8",
            ) as schema_file:
                json.dump(
                    _codex_output_schema(judgment_key),
                    schema_file,
                )
                schema_path = Path(schema_file.name)
            argv.extend(["--output-schema", str(schema_path)])

        argv.append("-")
        try:
            try:
                completed = subprocess.run(
                    argv,
                    input=run_prompt,
                    capture_output=True,
                    text=True,
                    encoding="utf-8",
                    timeout=self.timeout_s,
                )
            except FileNotFoundError as exc:
                raise RuntimeError(
                    _cli_launch_error("codex", self.cli, argv)
                ) from exc
        finally:
            if schema_path is not None:
                schema_path.unlink(missing_ok=True)

        if completed.returncode != 0:
            raise RuntimeError(
                f"codex CLI exited {completed.returncode}: "
                f"stderr={completed.stderr.strip()!r} "
                f"stdout={completed.stdout.strip()!r} "
                f"prompt_len={len(prompt)}"
            )
        response = completed.stdout
        payload = _extract_json_array(response)
        if len(payload) != expected:
            raise ValueError(
                f"Expected {expected} judgments, got {len(payload)}: {response!r}"
            )
        if self.cache is not None:
            self.cache.put(prompt, response)
        return payload


@dataclass
class AnthropicVertexJudge:
    """Judge that calls Anthropic Claude on Vertex AI directly via the SDK.

    Bypasses the Claude Code CLI wrapper, whose pre-screen classifier
    refuses oncology hypothesis text as "medical advice" even though the
    underlying model would happily evaluate it. Reuses the existing
    ``AnthropicVertexProvider`` so credentials follow the same env-var
    contract (``CLOUD_ML_REGION``, ``ANTHROPIC_VERTEX_PROJECT_ID``, ADC).
    """

    model_id: str = "claude-sonnet-4-6"
    region: str | None = None
    project_id: str | None = None
    batch_size: int = 10
    cache: JudgeCache | None = None
    max_tokens: int = 4096
    max_retries: int = 2

    def __post_init__(self) -> None:
        from ..providers.anthropic_vertex import (
            AnthropicVertexConfig,
            AnthropicVertexProvider,
        )

        self._provider = AnthropicVertexProvider(
            AnthropicVertexConfig(
                model_id=self.model_id,
                region=self.region,
                project_id=self.project_id,
                max_retries=self.max_retries,
            )
        )

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        out: list[NoveltyJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            payload = self._run_chunk(_build_novelty_prompt(chunk), expected=len(chunk))
            for entry in payload:
                out.append(
                    NoveltyJudgment(
                        is_novel=bool(entry.get("is_novel", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        out: list[MatchJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            prompt = _build_match_prompt(
                chunk, spec, variant=variant, column_mapping=column_mapping
            )
            payload = self._run_chunk(prompt, expected=len(chunk))
            for entry in payload:
                out.append(_match_judgment_from_payload(entry))
        return out

    def _run_chunk(self, prompt: str, *, expected: int) -> list[dict]:
        if self.cache is not None:
            cached = self.cache.get(prompt)
            if cached is not None:
                payload = _extract_json_array(cached)
                if len(payload) == expected:
                    return payload
        from ..providers.base import ChatMessage

        response = self._provider.chat(
            messages=[ChatMessage(role="user", content=prompt)],
            temperature=0.0,
            max_tokens=self.max_tokens,
        )
        text = response.text
        payload = _extract_json_array(text)
        if len(payload) != expected:
            raise ValueError(
                f"Expected {expected} judgments, got {len(payload)}: {text!r}"
            )
        if self.cache is not None:
            self.cache.put(prompt, text)
        return payload


@dataclass
class StubJudge:
    """Deterministic test-only judge.

    ``novel_phrases`` — substrings; a hypothesis is novel iff at least one
    matches.
    ``match_phrases`` — keyed by a substring of the rendered ground-truth
    spec block (e.g. a clinical word from the NL description, or a
    ``feature_NNN`` token from the variables list), maps to the set of
    hypothesis substrings that should match. The first key whose substring
    appears in the rendered block is the one applied.
    """

    novel_phrases: frozenset[str] = frozenset()
    match_phrases: dict[str, frozenset[str]] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.match_phrases is None:
            self.match_phrases = {}

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        return [
            NoveltyJudgment(
                is_novel=any(p.lower() in h.lower() for p in self.novel_phrases),
                rationale="stub",
            )
            for h in hypotheses
        ]

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        haystack = _render_spec_block(spec, variant, column_mapping).lower()
        active: frozenset[str] = frozenset()
        for key, phrases in self.match_phrases.items():
            if key.lower() in haystack:
                active = phrases
                break
        out: list[MatchJudgment] = []
        for hypothesis in hypotheses:
            matches = any(p.lower() in hypothesis.lower() for p in active)
            out.append(
                MatchJudgment(
                    matches=matches,
                    recovery_level="exact" if matches else "none",
                    rationale="stub",
                )
            )
        return out


def default_cache_dir() -> Path:
    return Path.home() / ".cache" / "onc-co-scientist" / "judge"
