"""LLM-backed judge for novelty + hypothesis-to-spec matching.

Two judgments share one interface so the on-disk cache and the backend
selector apply uniformly to both: ``judge_novelty`` (does each hypothesis
go beyond paradigm consensus?) and ``judge_matches`` (does each hypothesis
correspond to a single ground-truth association?).

Default backend is ``ClaudeCliJudge``: subprocess to ``claude
--dangerously-skip-permissions -p <prompt>`` so the judge runs under the
same Claude Code auth that's already on the box (no API key plumbing).
A deterministic ``StubJudge`` is provided for tests.

All judgments are cached on disk by ``sha256(prompt)`` so re-running
scoring on identical transcripts is free.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Protocol


@dataclass
class NoveltyJudgment:
    is_novel: bool
    rationale: str


@dataclass
class MatchJudgment:
    matches: bool
    rationale: str


class Judge(Protocol):
    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]: ...

    def judge_matches(
        self, hypotheses: list[str], association_nl: str
    ) -> list[MatchJudgment]: ...


# ---- Prompts ------------------------------------------------------------

_NOVELTY_PROMPT = """\
You are evaluating hypotheses generated by an analytical pipeline studying \
an oncology dataset. For each hypothesis, decide whether it is NOVEL — \
i.e., goes beyond established oncology paradigm consensus that would \
appear in a current treatment guideline or textbook for this disease. \
Standard known associations (e.g., "EGFR mutation predicts response to \
osimertinib", "BRCA1/2-mutant breast cancer responds to PARP inhibitors") \
are NOT novel. Speculative subgroup-conditional, mechanistic, or \
cross-pathway claims that wouldn't appear in a guideline ARE novel.

Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"is_novel": true|false, "rationale": "<one sentence>"}}, ...]
"""


_MATCH_PROMPT = """\
You are matching analyst-proposed hypotheses to a single ground-truth \
association embedded in a synthetic dataset. For each hypothesis, decide \
whether it semantically corresponds to the ground-truth association — \
variables, direction of effect, and any subgroup must align. Paraphrasing, \
synonym substitution, brand vs generic names, and mechanism-class \
language are fine.

Ground-truth association:
{association_nl}

Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"matches": true|false, "rationale": "<one sentence>"}}, ...]
"""


def _format_numbered(hypotheses: list[str]) -> str:
    return "\n".join(f"{i + 1}. {h}" for i, h in enumerate(hypotheses))


def _build_novelty_prompt(hypotheses: list[str]) -> str:
    return _NOVELTY_PROMPT.format(
        numbered=_format_numbered(hypotheses), n=len(hypotheses)
    )


def _build_match_prompt(hypotheses: list[str], association_nl: str) -> str:
    return _MATCH_PROMPT.format(
        association_nl=association_nl,
        numbered=_format_numbered(hypotheses),
        n=len(hypotheses),
    )


# ---- JSON extraction ----------------------------------------------------


def _extract_json_array(text: str) -> list[dict]:
    """Pull the outermost ``[...]`` block out of a possibly-wrapped LLM response.

    Handles preamble, code fences, and trailing commentary.
    """
    fence = re.search(r"```(?:json)?\s*(\[[\s\S]*?\])\s*```", text)
    if fence:
        payload = fence.group(1)
    else:
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1 or end <= start:
            raise ValueError(f"No JSON array found in response: {text!r}")
        payload = text[start : end + 1]
    parsed = json.loads(payload)
    if not isinstance(parsed, list):
        raise ValueError(f"Expected JSON array, got {type(parsed).__name__}: {parsed!r}")
    return parsed


# ---- Cache --------------------------------------------------------------


@dataclass
class JudgeCache:
    """Trivial sha256 → JSON file cache."""

    cache_dir: Path | None

    def get(self, prompt: str) -> str | None:
        if self.cache_dir is None:
            return None
        path = self._path(prompt)
        if not path.is_file():
            return None
        return path.read_text(encoding="utf-8")

    def put(self, prompt: str, response: str) -> None:
        if self.cache_dir is None:
            return
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        path = self._path(prompt)
        # Atomic: write temp, then rename.
        with tempfile.NamedTemporaryFile(
            mode="w", dir=self.cache_dir, delete=False, encoding="utf-8"
        ) as tmp:
            tmp.write(response)
            tmp_path = Path(tmp.name)
        os.replace(tmp_path, path)

    def _path(self, prompt: str) -> Path:
        assert self.cache_dir is not None
        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        return self.cache_dir / f"{digest}.txt"


# ---- Backends -----------------------------------------------------------


def _chunked(items: list[str], n: int) -> Iterable[list[str]]:
    for i in range(0, len(items), n):
        yield items[i : i + n]


@dataclass
class ClaudeCliJudge:
    """Default judge: shells out to the ``claude`` CLI with ``-p``.

    Requires a working ``claude`` on ``PATH`` (or pass ``cli=...``). No API
    key needed when running on a host where Claude Code is already
    authenticated.
    """

    cli: str = "claude"
    extra_args: tuple[str, ...] = (
        "--dangerously-skip-permissions",
    )
    batch_size: int = 10
    cache: JudgeCache | None = None
    timeout_s: int = 600

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        out: list[NoveltyJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            payload = self._run_chunk(_build_novelty_prompt(chunk), expected=len(chunk))
            for entry in payload:
                out.append(
                    NoveltyJudgment(
                        is_novel=bool(entry.get("is_novel", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def judge_matches(
        self, hypotheses: list[str], association_nl: str
    ) -> list[MatchJudgment]:
        out: list[MatchJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            prompt = _build_match_prompt(chunk, association_nl)
            payload = self._run_chunk(prompt, expected=len(chunk))
            for entry in payload:
                out.append(
                    MatchJudgment(
                        matches=bool(entry.get("matches", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def _run_chunk(self, prompt: str, *, expected: int) -> list[dict]:
        if self.cache is not None:
            cached = self.cache.get(prompt)
            if cached is not None:
                payload = _extract_json_array(cached)
                if len(payload) == expected:
                    return payload
                # Cache mismatch on length — fall through and re-call.
        argv = [self.cli, *self.extra_args, "-p", prompt]
        completed = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=self.timeout_s,
        )
        if completed.returncode != 0:
            raise RuntimeError(
                f"claude CLI exited {completed.returncode}: {completed.stderr.strip()!r}"
            )
        response = completed.stdout
        payload = _extract_json_array(response)
        if len(payload) != expected:
            raise ValueError(
                f"Expected {expected} judgments, got {len(payload)}: {response!r}"
            )
        if self.cache is not None:
            self.cache.put(prompt, response)
        return payload


@dataclass
class StubJudge:
    """Deterministic test-only judge.

    ``novel_phrases`` — substrings; a hypothesis is novel iff at least one
    matches.
    ``match_phrases`` — keyed by association_nl substring (an entry that
    appears within the spec's natural-language description), maps to the
    set of hypothesis substrings that should match.
    """

    novel_phrases: frozenset[str] = frozenset()
    match_phrases: dict[str, frozenset[str]] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.match_phrases is None:
            self.match_phrases = {}

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        return [
            NoveltyJudgment(
                is_novel=any(p.lower() in h.lower() for p in self.novel_phrases),
                rationale="stub",
            )
            for h in hypotheses
        ]

    def judge_matches(
        self, hypotheses: list[str], association_nl: str
    ) -> list[MatchJudgment]:
        # Pick the first match-key whose substring appears in the spec NL.
        active: frozenset[str] = frozenset()
        for key, phrases in self.match_phrases.items():
            if key.lower() in association_nl.lower():
                active = phrases
                break
        return [
            MatchJudgment(
                matches=any(p.lower() in h.lower() for p in active),
                rationale="stub",
            )
            for h in hypotheses
        ]


def default_cache_dir() -> Path:
    return Path.home() / ".cache" / "onc-co-scientist" / "judge"
