"""LLM-backed judge for novelty + hypothesis-to-spec matching.

Two judgments share one interface so the on-disk cache and the backend
selector apply uniformly to both: ``judge_novelty`` (does each hypothesis
go beyond paradigm consensus?) and ``judge_matches`` (does each hypothesis
correspond to a single ground-truth association?).

``judge_matches`` is variant-aware but the *information shown to the
judge* is symmetric across variants: when a column mapping is
available the rendered ground-truth block includes both the clinical
name and the corresponding ``feature_NNN`` identifier for every
variable and predicate key, and the free-text NL description is shown
for both variants. The variant only determines which column-name
space the agent's hypothesis text uses; the judge sees both spaces
either way.

Default backend is ``ClaudeCliJudge``: subprocess to ``claude
--dangerously-skip-permissions -p <prompt>`` so the judge runs under the
same Claude Code auth that's already on the box (no API key plumbing).
A deterministic ``StubJudge`` is provided for tests.

All judgments are cached on disk by ``sha256(prompt)`` so re-running
scoring on identical transcripts is free.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal, Protocol

from ..synthetic.schemas import AssociationForm, AssociationSpec

Variant = Literal["named", "anonymized"]


@dataclass
class NoveltyJudgment:
    is_novel: bool
    rationale: str


@dataclass
class MatchJudgment:
    matches: bool
    rationale: str


class Judge(Protocol):
    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]: ...

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]: ...


# ---- Prompts ------------------------------------------------------------

_NOVELTY_PROMPT = """\
You are evaluating hypotheses generated by an analytical pipeline studying \
an oncology dataset. For each hypothesis, decide whether it is NOVEL — \
i.e., goes beyond established oncology paradigm consensus that would \
appear in a current treatment guideline or textbook for this disease. \
Standard known associations (e.g., "EGFR mutation predicts response to \
osimertinib", "BRCA1/2-mutant breast cancer responds to PARP inhibitors") \
are NOT novel. Speculative subgroup-conditional, mechanistic, or \
cross-pathway claims that wouldn't appear in a guideline ARE novel.

Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"is_novel": true|false, "rationale": "<one sentence>"}}, ...]
"""


_MATCH_PROMPT = """\
You are matching analyst-proposed hypotheses to a single ground-truth \
association embedded in a synthetic dataset. For each hypothesis, decide \
whether it would, if confirmed, correspond to the ground-truth association \
— i.e. whether it identifies (or proposes a method capable of identifying) \
the same data-generating process.

A hypothesis MATCHES if all the following hold:
1. It points at the same set of feature/variable column(s) and the same \
outcome column listed in the spec. Each variable below is shown with \
both its clinical name and the corresponding anonymized identifier \
(``feature_NNN``) where applicable; the analyst was given only one of \
these two name spaces, so a hypothesis that uses either name is referring \
to the same underlying column. Treat clinical names and ``feature_NNN`` \
identifiers as fully interchangeable.
2. It describes (or proposes to investigate) the same relationship. \
Paraphrasing, synonyms, brand-vs-generic names, and mechanism-class \
language are fine. The hypothesis does NOT have to specify the exact \
functional form: a hypothesis that proposes investigating these variables \
with a method reasonably expected to capture the spec's functional form \
counts as matching — e.g. a tree ensemble or interaction-aware model for \
an interaction; subgroup analysis, stratification, or a heterogeneous- \
treatment-effect model for a subgroup-conditional effect; a regression \
or test of association for a main effect.
3. The direction of effect, if specified by the hypothesis, agrees with \
the ground truth.

Ground-truth association:
{spec_block}
Hypotheses (one per item, indexed in order):
{numbered}

Respond with ONLY a JSON array of length {n}, one entry per hypothesis in \
the same order:
[{{"matches": true|false, "rationale": "<one sentence>"}}, ...]
"""


_FORM_HUMAN: dict[AssociationForm, str] = {
    AssociationForm.main_effect: (
        "main effect — the variable directly predicts the outcome"
    ),
    AssociationForm.interaction: (
        "interaction — two or more variables jointly affect the outcome "
        "(effects depend on combinations of values, not each variable alone)"
    ),
    AssociationForm.subgroup_conditional: (
        "subgroup-conditional — the relationship is active only within a "
        "defined subset of patients"
    ),
}


def _direction_human(direction: int) -> str:
    if direction > 0:
        return "positive (increases the outcome)"
    if direction < 0:
        return "negative (decreases the outcome)"
    return "null / no expected directional effect"


def _format_numbered(hypotheses: list[str]) -> str:
    return "\n".join(f"{i + 1}. {h}" for i, h in enumerate(hypotheses))


def _bilingual_name(
    col: str,
    forward: dict[str, str] | None,
    inverse: dict[str, str] | None,
) -> str:
    """Render ``col`` as ``clinical (anonymized: feature_NNN)`` when both
    sides are available; otherwise return ``col`` verbatim.

    ``forward`` is ``{clinical → feature_NNN}``; ``inverse`` is its reverse.
    Outcome and id columns are excluded from anonymization (they appear
    verbatim in both spaces) and so end up in neither map — those return
    ``col`` unchanged.
    """
    if forward is None:
        return col
    if col in forward:
        return f"{col} (anonymized: {forward[col]})"
    if inverse is not None and col in inverse:
        return f"{inverse[col]} (anonymized: {col})"
    return col


def _render_spec_block(
    spec: AssociationSpec,
    variant: Variant,
    column_mapping: dict[str, str] | None = None,
) -> str:
    """Render the structured ground-truth block of the match prompt.

    Variables and (subgroup) predicate keys are rendered bilingually when
    ``column_mapping`` is provided (``{clinical → feature_NNN}``) so the
    judge sees the same information regardless of which variant the agent
    saw. The free-text NL description is included for both variants.
    """
    inverse = (
        {v: k for k, v in column_mapping.items()}
        if column_mapping is not None
        else None
    )

    lines: list[str] = []
    lines.append(f"- Outcome column: {spec.outcome}")
    lines.append("- Variables involved:")
    for v in spec.variables:
        lines.append(f"    * {_bilingual_name(v, column_mapping, inverse)}")
    lines.append(f"- Functional form: {_FORM_HUMAN[spec.form]}")
    if spec.subgroup is not None:
        lines.append(
            f"- Subgroup (relationship active only here): "
            f"{spec.subgroup.description}"
        )
        for k, val in spec.subgroup.predicate.items():
            lines.append(
                f"    * Predicate: {_bilingual_name(k, column_mapping, inverse)} = {val}"
            )
    lines.append(f"- Direction of effect on outcome: {_direction_human(spec.direction)}")
    lines.append(
        f"- Plain-English description: {spec.natural_language_description}"
    )
    return "\n".join(lines) + "\n"


def _build_novelty_prompt(hypotheses: list[str]) -> str:
    return _NOVELTY_PROMPT.format(
        numbered=_format_numbered(hypotheses), n=len(hypotheses)
    )


def _build_match_prompt(
    hypotheses: list[str],
    spec: AssociationSpec,
    *,
    variant: Variant,
    column_mapping: dict[str, str] | None = None,
) -> str:
    return _MATCH_PROMPT.format(
        spec_block=_render_spec_block(spec, variant, column_mapping),
        numbered=_format_numbered(hypotheses),
        n=len(hypotheses),
    )


# ---- JSON extraction ----------------------------------------------------


def _extract_json_array(text: str) -> list[dict]:
    """Pull the outermost ``[...]`` block out of a possibly-wrapped LLM response.

    Handles preamble, code fences, and trailing commentary.
    """
    fence = re.search(r"```(?:json)?\s*(\[[\s\S]*?\])\s*```", text)
    if fence:
        payload = fence.group(1)
    else:
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1 or end <= start:
            raise ValueError(f"No JSON array found in response: {text!r}")
        payload = text[start : end + 1]
    parsed = json.loads(payload)
    if not isinstance(parsed, list):
        raise ValueError(f"Expected JSON array, got {type(parsed).__name__}: {parsed!r}")
    return parsed


# ---- Cache --------------------------------------------------------------


@dataclass
class JudgeCache:
    """Trivial sha256 → JSON file cache."""

    cache_dir: Path | None

    def get(self, prompt: str) -> str | None:
        if self.cache_dir is None:
            return None
        path = self._path(prompt)
        if not path.is_file():
            return None
        return path.read_text(encoding="utf-8")

    def put(self, prompt: str, response: str) -> None:
        if self.cache_dir is None:
            return
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        path = self._path(prompt)
        # Atomic: write temp, then rename.
        with tempfile.NamedTemporaryFile(
            mode="w", dir=self.cache_dir, delete=False, encoding="utf-8"
        ) as tmp:
            tmp.write(response)
            tmp_path = Path(tmp.name)
        os.replace(tmp_path, path)

    def _path(self, prompt: str) -> Path:
        assert self.cache_dir is not None
        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        return self.cache_dir / f"{digest}.txt"


# ---- Backends -----------------------------------------------------------


def _chunked(items: list[str], n: int) -> Iterable[list[str]]:
    for i in range(0, len(items), n):
        yield items[i : i + n]


@dataclass
class ClaudeCliJudge:
    """Default judge: shells out to the ``claude`` CLI with ``-p``.

    Requires a working ``claude`` on ``PATH`` (or pass ``cli=...``). No API
    key needed when running on a host where Claude Code is already
    authenticated.
    """

    cli: str = "claude"
    extra_args: tuple[str, ...] = (
        "--dangerously-skip-permissions",
    )
    batch_size: int = 10
    cache: JudgeCache | None = None
    timeout_s: int = 600

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        out: list[NoveltyJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            payload = self._run_chunk(_build_novelty_prompt(chunk), expected=len(chunk))
            for entry in payload:
                out.append(
                    NoveltyJudgment(
                        is_novel=bool(entry.get("is_novel", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        out: list[MatchJudgment] = []
        for chunk in _chunked(hypotheses, self.batch_size):
            prompt = _build_match_prompt(
                chunk, spec, variant=variant, column_mapping=column_mapping
            )
            payload = self._run_chunk(prompt, expected=len(chunk))
            for entry in payload:
                out.append(
                    MatchJudgment(
                        matches=bool(entry.get("matches", False)),
                        rationale=str(entry.get("rationale", "")),
                    )
                )
        return out

    def _run_chunk(self, prompt: str, *, expected: int) -> list[dict]:
        if self.cache is not None:
            cached = self.cache.get(prompt)
            if cached is not None:
                payload = _extract_json_array(cached)
                if len(payload) == expected:
                    return payload
                # Cache mismatch on length — fall through and re-call.
        argv = [self.cli, *self.extra_args, "-p", prompt]
        completed = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=self.timeout_s,
        )
        if completed.returncode != 0:
            raise RuntimeError(
                f"claude CLI exited {completed.returncode}: {completed.stderr.strip()!r}"
            )
        response = completed.stdout
        payload = _extract_json_array(response)
        if len(payload) != expected:
            raise ValueError(
                f"Expected {expected} judgments, got {len(payload)}: {response!r}"
            )
        if self.cache is not None:
            self.cache.put(prompt, response)
        return payload


@dataclass
class StubJudge:
    """Deterministic test-only judge.

    ``novel_phrases`` — substrings; a hypothesis is novel iff at least one
    matches.
    ``match_phrases`` — keyed by a substring of the rendered ground-truth
    spec block (e.g. a clinical word from the NL description, or a
    ``feature_NNN`` token from the variables list), maps to the set of
    hypothesis substrings that should match. The first key whose substring
    appears in the rendered block is the one applied.
    """

    novel_phrases: frozenset[str] = frozenset()
    match_phrases: dict[str, frozenset[str]] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.match_phrases is None:
            self.match_phrases = {}

    def judge_novelty(self, hypotheses: list[str]) -> list[NoveltyJudgment]:
        return [
            NoveltyJudgment(
                is_novel=any(p.lower() in h.lower() for p in self.novel_phrases),
                rationale="stub",
            )
            for h in hypotheses
        ]

    def judge_matches(
        self,
        hypotheses: list[str],
        spec: AssociationSpec,
        *,
        variant: Variant,
        column_mapping: dict[str, str] | None = None,
    ) -> list[MatchJudgment]:
        haystack = _render_spec_block(spec, variant, column_mapping).lower()
        active: frozenset[str] = frozenset()
        for key, phrases in self.match_phrases.items():
            if key.lower() in haystack:
                active = phrases
                break
        return [
            MatchJudgment(
                matches=any(p.lower() in h.lower() for p in active),
                rationale="stub",
            )
            for h in hypotheses
        ]


def default_cache_dir() -> Path:
    return Path.home() / ".cache" / "onc-co-scientist" / "judge"
